#https://cloud.google.com/functions/docs/testing/test-cicd#functions-prepare-environment-nodejs

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: './'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: './'

  ## Function helloGet
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['functions', 'deploy', 'helloGet', '--runtime', 'nodejs12', '--trigger-http',  '--allow-unauthenticated']

  ## Function helloEnv
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['functions', 'deploy', 'helloEnv', '--runtime', 'nodejs12', '--trigger-http',  '--allow-unauthenticated']

  ## Function helloContent
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['functions', 'deploy', 'helloContent', '--runtime', 'nodejs12', '--trigger-http',  '--allow-unauthenticated']